title: Ibiza Properties
#email: your-email@example.com
description: >-
    Find your perfect Ibiza property with our comprehensive listings. Browse through our diverse range of properties, from luxury villas to cozy apartments, all available for sale or rental.
baseurl: "/ibiza-realestate-jekyll/" # the subpath of your site, e.g. /blog
url: "https://judsonlmoore.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  judsonlmoore

plugins:
  - jekyll-feed
  - jekyll-datapage-generator

collections: 
  pages:
    output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site/pagefind/

page_gen-dirs: true
page_gen:
- data: listings
  template: listing
  dir: listings
  index_files: true
  name: property_id
  #name_expr: [a Ruby expression to generate the filename (alternative to name)]
  title: title
  #title_expr: [a Ruby expression to generate the filename (alternative to title)]
  #extension: [extension used to generate the filename.]
  #filter: [property to filter data records by]
  #filter_condition: [a Ruby expression to filter data]
  #page_data_prefix: [prefix used to name variables]
  #debug: [boolean, if true output more informative messages]

# Keep pagefind directory during builds
keep_files:
  - pagefind